### ISSUE TITLE
Not Working on Ubuntu 18.04

### ISSUE THREAD

**Issue by khurshid-alam** [dbader/schedule#359]
I get this error

File "sch.py", line 10, in <module>
    schedule.every(5).to(10).minutes.do(job)
AttributeError: 'Job' object has no attribute 'to'

Please update the doc

**Comment by SijmenHuizenga** [comment]
Hi there! `schedule.every(5).to(10).minutes.do(job)` _is_ valid syntax. Please check if you are using the latest version of the library using `pip3 list | grep schedule`.

**Comment by SijmenHuizenga** [comment]
I assume the issue was resolved since the conversation has stalled. If that is not the case, feel free to create a new issue.
